%%{init: {'theme': 'default', 'themeVariables': {'fontFamily': 'sans-serif'}, 'flowchart': {'htmlLabels': true}}}%%
flowchart TD
    bpmn_start_event(["[issue getest]"])
    bpmn_task_intake["Demonstratie van de<br>oplossing geven"]
    bpmn_gateway_fork{"+"}
    bpmn_event_notification(("[automatische<br>notificatie<br>verzonden]"))
    bpmn_gateway_join{"+"}
    bpmn_task_beoordeling["Review met Jeroen<br>uitvoeren"]
    bpmn_task_analyse["Zet Jira uitvoerder<br>op de baas"]
    bpmn_end_event(["[issue gesloten]"])
    mIc6XLMKuAxiAPNymMe0-20["Medewerker"]
    mIc6XLMKuAxiAPNymMe0-21["Opdrachtgever"]
    bpmn_gateway_xor -->|"[goedgekeurd]"| bpmn_task_analyse
    bpmn_gateway_xor -->|"[afgekeurd]"| bpmn_task_intake
    bpmn_start_event --> bpmn_task_intake
    bpmn_task_intake --> bpmn_gateway_fork
    bpmn_gateway_fork --> bpmn_event_notification
    bpmn_event_notification --> bpmn_gateway_join
    bpmn_gateway_fork --> bpmn_gateway_join
    bpmn_gateway_join --> bpmn_task_beoordeling
    bpmn_task_beoordeling --> bpmn_gateway_xor
    bpmn_task_analyse --> bpmn_end_event
