%%{init: {'theme': 'default', 'themeVariables': {'fontFamily': 'sans-serif'}, 'flowchart': {'htmlLabels': false}}}%%
flowchart TD
    bpmn_start_event(["[issue getest]"])
    bpmn_task_intake["Demonstratie van de\noplossing geven"]
    bpmn_gateway_fork{"+"}
    bpmn_event_notification(("[automatische\nnotificatie\nverzonden]"))
    bpmn_gateway_join{"+"}
    bpmn_task_beoordeling["Review met Jeroen\nuitvoeren"]
    bpmn_task_analyse["Zet Jira uitvoerder\nop de baas"]
    bpmn_end_event(["[issue gesloten]"])
    mIc6XLMKuAxiAPNymMe0-20["Medewerker"]
    mIc6XLMKuAxiAPNymMe0-21["Opdrachtgever"]
    bpmn_gateway_xor -->|"[goedgekeurd]"| bpmn_task_analyse
    bpmn_gateway_xor -->|"[afgekeurd]"| bpmn_task_intake
    bpmn_start_event --> bpmn_task_intake
    bpmn_task_intake --> bpmn_gateway_fork
    bpmn_gateway_fork --> bpmn_event_notification
    bpmn_event_notification --> bpmn_gateway_join
    bpmn_gateway_fork --> bpmn_gateway_join
    bpmn_gateway_join --> bpmn_task_beoordeling
    bpmn_task_beoordeling --> bpmn_gateway_xor
    bpmn_task_analyse --> bpmn_end_event
