flowchart TD
    bpmn_start_event(["[speciale actie uitgevoerd]"])
    bpmn_task_intake["Uitvoeren gezamenlijk speciale actie review"]
    bpmn_event_notification(("[automatische notificatie verzonden]"))
    bpmn_task_beoordeling["Beoordelen resultaat"]
    bpmn_task_analyse["Zet Jira uitvoerder op de baas"]
    bpmn_end_event(["[speciale actie goedgekeurd]"])
    mIc6XLMKuAxiAPNymMe0-20["Medewerker"]
    mIc6XLMKuAxiAPNymMe0-21["Opdrachtgever"]
    bpmn_gateway_xor -->|"[goedgekeurd]"| bpmn_task_analyse
    bpmn_gateway_xor -->|"[afgekeurd]"| bpmn_task_intake
    bpmn_start_event --> bpmn_task_intake
    bpmn_task_intake --> bpmn_gateway_fork
    bpmn_gateway_fork --> bpmn_event_notification
    bpmn_event_notification --> bpmn_gateway_join
    bpmn_gateway_fork --> bpmn_gateway_join
    bpmn_gateway_join --> bpmn_task_beoordeling
    bpmn_task_beoordeling --> bpmn_gateway_xor
    bpmn_task_analyse --> bpmn_end_event
