flowchart TD
    bpmn_start_event(["[ontwerp goedgekeurd]"])
    bpmn_task_intake["Ontwerp verwerken"]
    bpmn_task_oplossing["Oplossing implementeren"]
    bpmn_event_etc(("[na 2/3, 100% of 150% ETC]"))
    bpmn_task_inschatting["Hoe lang denk je nog nodig te hebben?"]
    bpmn_task_verantwoording["Hoe heeft het zo lang kunnen duren?"]
    bpmn_end_regulier(["[volg de test]"])
    bpmn_end_bijzonderheden(["[volg de meldplicht]"])
    bpmn_gateway_kwaliteit -->|"[onvolledig]"| bpmn_task_intake
    bpmn_gateway_kwaliteit -->|"[volledig]"| bpmn_gateway_join
    bpmn_gateway_haalbaarheid -->|"[haalbaar]"| bpmn_gateway_join
    bpmn_gateway_haalbaarheid -->|"[onhaalbaar]"| bpmn_task_verantwoording
    bpmn_gateway_bijzonderheden -->|"[geen bijzonderheden]"| bpmn_end_regulier
    bpmn_gateway_bijzonderheden -->|"[bijzonderheden]"| bpmn_end_bijzonderheden
    bpmn_start_event --> bpmn_gateway_fork
    bpmn_gateway_fork --> bpmn_task_intake
    bpmn_gateway_fork --> bpmn_event_etc
    bpmn_task_intake --> bpmn_task_oplossing
    bpmn_task_oplossing --> bpmn_gateway_kwaliteit
    bpmn_event_etc --> bpmn_task_inschatting
    bpmn_task_inschatting --> bpmn_gateway_haalbaarheid
    bpmn_task_verantwoording --> bpmn_gateway_join
    bpmn_gateway_join --> bpmn_gateway_bijzonderheden
