%%{init: {'theme': 'default', 'themeVariables': {'fontFamily': 'sans-serif'}, 'flowchart': {'htmlLabels': false}}}%%
flowchart TD
    bpmn_start_event(["[meldplicht\ngetriggerd]"])
    bpmn_task_start_timer["Start timer (5 min)"]
    bpmn_task_stel_plan_op["Stel vervolgplan op"]
    bpmn_task_stop_timer["Stop timer (5 min)"]
    bpmn_task_baas_aanwezig["Is de baas aanwezig?\n(indien niet\naanwezig: wachten)"]
    bpmn_task_overleg["Overleg vervolgplan"]
    bpmn_task_status["De baas bepaalt\nvolgende status"]
    bpmn_task_effort["De baas verifieert\neffort per\nresterende fase"]
    bpmn_task_volg_status["Volg de afgestemde\nstatus"]
    bpmn_end_event(["[meldplicht\nvoltooid]"])
    mIc6XLMKuAxiAPNymMe0-20["Medewerker"]
    mIc6XLMKuAxiAPNymMe0-21["Opdrachtgever"]
    bpmn_start_event --> bpmn_task_start_timer
    bpmn_task_start_timer --> bpmn_task_stel_plan_op
    bpmn_task_stel_plan_op --> bpmn_task_stop_timer
    bpmn_task_stop_timer --> bpmn_task_baas_aanwezig
    bpmn_task_baas_aanwezig --> bpmn_task_overleg
    bpmn_task_overleg --> bpmn_task_status
    bpmn_task_status --> bpmn_task_effort
    bpmn_task_effort --> bpmn_task_volg_status
    bpmn_task_volg_status --> bpmn_end_event
