use super::*;
// All test workbooks are constructed here in memory. Never read the real workbook.
fn fixture()->(Package,Manifest){
    let m=manifest().unwrap();let mut texts=vec!["synthetic".to_string();490];for d in &m.cells{if let Some(i)=d.old_ref{texts[i]=d.old.clone().unwrap();}}texts[36]="shared old index36".into();
    let mut entries=BTreeMap::new();let sst=format!("<?xml version=\"1.0\" encoding=\"UTF-8\"?><sst xmlns=\"{NS}\" xmlns:x=\"urn:unknown\" count=\"1163\" uniqueCount=\"490\">{}<x:extension untouched='yes'/></sst>",texts.iter().enumerate().map(|(i,t)|if i==36{format!("<si><r><rPr><b/></rPr><t xml:space=\"preserve\">{}</t></r></si>",quick_xml::escape::escape(t))}else{format!("<si><t>{}</t></si>",quick_xml::escape::escape(t))}).collect::<String>());entries.insert(PARTS[0].to_string(),sst.into_bytes());
    for sheet in 1..=3{let rows=[0,12,130,110][sheet];let mut xml=format!("<?xml version='1.0'?><worksheet xmlns=\"{NS}\" xmlns:x='urn:unknown'><dimension ref='A1:E{rows}'/><sheetData>");for row in 1..=rows{xml.push_str(&format!("<row r='{row}'>"));for col in b'A'..=b'E'{let c=format!("{}{row}",col as char);let d=m.cells.iter().find(|d|d.sheet==sheet&&d.cell==c);let empty=sheet==3 && ((row==91 && col>=b'C') || (row>=92 && !(row==94 && col==b'C')));if !empty{let reference=d.and_then(|d|d.old_ref).unwrap_or(36);xml.push_str(&format!("<c r='{c}' s='3' t='s'><v>{reference}</v><extLst><x:unknown a='keep'/></extLst></c>"));}else{xml.push_str(&format!("<c r='{c}' s='3'/>"));}}xml.push_str("</row>");}xml.push_str("</sheetData>");if sheet==3{xml.push_str("<conditionalFormatting sqref='A2:E110'>");for i in 0..12{xml.push_str(&format!("<cfRule type='expression' dxfId='{i}' priority='{}'><formula>$B2=\"Intake\"</formula></cfRule>",i+1));}xml.push_str("</conditionalFormatting>");}xml.push_str("<extLst><x:opaque> &amp; unchanged </x:opaque></extLst></worksheet>");entries.insert(PARTS[sheet].into(),xml.into_bytes());}
    entries.insert("xl/styles.xml".into(),format!("<styleSheet xmlns='{NS}'><cellXfs count='4'><xf/><xf/><xf/><xf/></cellXfs></styleSheet>").into_bytes());
    entries.insert("xl/workbook.xml".into(),format!("<workbook xmlns='{NS}' xmlns:r='{REL}'><sheets>{}</sheets></workbook>",m.bindings.iter().enumerate().map(|(i,b)|format!("<sheet name='{}' sheetId='{}' r:id='{}'/>",b[0],i+1,b[1])).collect::<String>()).into_bytes());
    entries.insert("xl/_rels/workbook.xml.rels".into(),format!("<Relationships xmlns='{PKGREL}'>{}</Relationships>",m.bindings.iter().map(|b|format!("<Relationship Id='{}' Type='{REL}/worksheet' Target='{}'/>",b[1],b[2])).collect::<String>()).into_bytes());entries.insert("unknown/protected.bin".into(),vec![0,255,10,1]);
    let mut writer=ZipWriter::new(Cursor::new(Vec::new()));for(n,b)in entries{writer.start_file(n,SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated)).unwrap();writer.write_all(&b).unwrap();}let bytes=writer.finish().unwrap().into_inner();(package(&bytes).unwrap(),m)
}
fn mutated(part:&str,old:&str,new:&str)->(Package,Manifest){let(mut p,m)=fixture();let e=p.get_mut(part).unwrap();let s=String::from_utf8(e.data.clone()).unwrap();assert!(s.contains(old));e.data=s.replacen(old,new,1).into_bytes();(p,m)}
#[test]fn complete_selective_change_preserves_all_original_spans(){let(p,m)=fixture();let changes=transform(&p,&m).unwrap();let mut q=p.clone();for(n,b)in &changes{q.get_mut(n).unwrap().data=b.clone();}verify(&p,&q,&m,&changes).unwrap();assert_eq!(changes.len(),4);}
#[test]fn old36_copy_on_write_target_only(){let bytes=format!("<sst xmlns='{NS}' count='2' uniqueCount='37'>{}<si><r><t xml:space='preserve'> old &amp; text </t></r></si></sst>","<si><t>filler</t></si>".repeat(36));let x=Xml::parse(bytes.as_bytes()).unwrap();let ss=items(&x).unwrap();assert_eq!(si_text(&x,ss[36]).unwrap()," old & text ");let source=format!("<worksheet xmlns='{NS}'><sheetData><row r='1'><c r='A1' t='s'><v>36</v></c><c r='B1' t='s'><v>36</v></c></row></sheetData></worksheet>");let x=Xml::parse(source.as_bytes()).unwrap();let map=cell_map(&x).unwrap();let v=x.children(map["A1"],"v")[0];let n=&x.nodes[v];let changed=apply(x.bytes,vec![Patch{start:n.open_end,end:n.close_start,text:b"37".to_vec()}]).unwrap();let y=Xml::parse(&changed).unwrap();let ym=cell_map(&y).unwrap();assert_eq!(x.raw(map["B1"]),y.raw(ym["B1"]));assert_eq!(y.content(y.children(ym["A1"],"v")[0]).unwrap(),"37");}
#[test]fn wrong_old_ref_blocked(){let(p,m)=mutated(PARTS[1],"<v>12</v>","<v>36</v>");assert!(transform(&p,&m).is_err());}
#[test]fn wrong_old_text_blocked(){let(p,m)=mutated(PARTS[0],"<t>Analyse</t>","<t>WRONG</t>");assert!(transform(&p,&m).is_err());}
#[test]fn formula_blocked(){let(p,m)=mutated(PARTS[1],"<v>12</v>","<f>1+1</f><v>12</v>");assert!(transform(&p,&m).is_err());}
#[test]fn new_cell_conflict_blocked(){let(p,m)=mutated(PARTS[3],"</row>","<c r='F1' t='s'><v>36</v></c></row>");assert!(transform(&p,&m).is_err());}
#[test]fn malformed_ref_blocked(){for c in ["A0","A01","a1","A-1","1","A1:B1","XFE1","A1048577","AAA"]{assert!(coord(c).is_err(),"{c}");}let(p,m)=mutated(PARTS[1],"r='A1'","r='A01'");assert!(transform(&p,&m).is_err());}
#[test]fn duplicate_and_excluded_targets_blocked(){let(_,mut m)=fixture();m.cells[1]=m.cells[0].clone();assert!(validate_deltas(&m).is_err());let mut m=manifest().unwrap();m.cells[0].cell="E3".into();assert!(validate_deltas(&m).is_err());}
#[test]fn unknown_target_and_allowlist_mutation_blocked(){let mut m=manifest().unwrap();m.cells[0].sheet=4;assert!(validate_deltas(&m).is_err());let mut m=manifest().unwrap();m.allowed_parts.push("xl/styles.xml".into());assert!(validate_deltas(&m).is_err());let json=APPROVED.replace("Analysing","Fake");assert!(check_manifest(&json).is_err());}
#[test]fn relation_binding_blocked(){let(p,m)=mutated("xl/_rels/workbook.xml.rels","worksheets/sheet1.xml","worksheets/evil.xml");assert!(transform(&p,&m).is_err());}
#[test]fn namespace_and_malformed_xml_blocked(){assert!(Xml::parse(b"<x><y></x>").is_err());let(p,m)=mutated(PARTS[3],NS,"urn:wrong");assert!(transform(&p,&m).is_err());assert!(Xml::parse(b"<!DOCTYPE x><x/>").is_err());}
#[test]fn independent_preservation_tamper_detected(){let(p,m)=fixture();let changes=transform(&p,&m).unwrap();let mut q=p.clone();for(n,b)in &changes{q.get_mut(n).unwrap().data=b.clone();}q.get_mut("unknown/protected.bin").unwrap().raw.push(1);assert!(verify(&p,&q,&m,&changes).is_err());}
#[test]fn source_hash_and_no_writes_on_failure(){let dir=tempfile::tempdir().unwrap();let manifest_path=dir.path().join("manifest.json");fs::write(&manifest_path,APPROVED).unwrap();fs::create_dir(dir.path().join("Megalijst")).unwrap();fs::write(dir.path().join("Megalijst/issue-tracker-overzicht.xlsx"),b"wrong hash").unwrap();let out=dir.path().join("existing.xlsx");fs::write(&out,b"do not overwrite").unwrap();assert!(run(dir.path(),&manifest_path,Some(&out)).is_err());assert_eq!(fs::read(out).unwrap(),b"do not overwrite");assert_eq!(fs::read(dir.path().join("Megalijst/issue-tracker-overzicht.xlsx")).unwrap(),b"wrong hash");}
#[test]fn zip_raw_copy_proven(){let(p,_)=fixture();let source=&p["unknown/protected.bin"];let mut writer=ZipWriter::new(Cursor::new(vec![]));writer.start_file("a",SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated)).unwrap();writer.write_all(&source.data).unwrap();let bytes=writer.finish().unwrap().into_inner();let original=package(&bytes).unwrap();let mut z=ZipArchive::new(Cursor::new(&bytes)).unwrap();let mut out=ZipWriter::new(Cursor::new(vec![]));out.raw_copy_file(z.by_index(0).unwrap()).unwrap();let copied=package(&out.finish().unwrap().into_inner()).unwrap();assert_eq!(original["a"].raw,copied["a"].raw);assert_eq!(original["a"].data,copied["a"].data);}
#[test]fn synthetic_candidate_actual_zip_reopen_and_no_clobber(){
    let(p,m)=fixture();let changes=transform(&p,&m).unwrap();let mut source=ZipWriter::new(Cursor::new(vec![]));
    for(n,e)in &p{source.start_file(n,SimpleFileOptions::default().compression_method(e.method)).unwrap();source.write_all(&e.data).unwrap();}
    let bytes=source.finish().unwrap().into_inner();let original=package(&bytes).unwrap();let dir=tempfile::tempdir().unwrap();let out=dir.path().join("synthetic.xlsx");let mut temp=new_candidate(&out).unwrap();write_zip(&bytes,&changes,temp.as_file_mut()).unwrap();temp.as_file().sync_all().unwrap();let candidate=package(&fs::read(temp.path()).unwrap()).unwrap();verify(&original,&candidate,&m,&changes).unwrap();publish(temp,&out).unwrap();let published=fs::read(&out).unwrap();assert!(new_candidate(&out).is_err());let mut race=tempfile::NamedTempFile::new_in(dir.path()).unwrap();race.write_all(b"must not replace").unwrap();assert!(publish(race,&out).is_err());assert_eq!(fs::read(out).unwrap(),published);
}
#[test]fn metadata_and_unknown_spans_tamper_blocked(){let(p,m)=fixture();let changes=transform(&p,&m).unwrap();let mut q=p.clone();for(n,b)in &changes{q.get_mut(n).unwrap().data=b.clone();}let e=q.get_mut(PARTS[3]).unwrap();e.data=String::from_utf8(e.data.clone()).unwrap().replace("A2:G110","A2:H110").into_bytes();assert!(verify(&p,&q,&m,&changes).is_err());}
#[test]fn escape_space_and_prefix_preserved(){let xml=b"<?xml version='1.0'?><s:sst xmlns:s='http://schemas.openxmlformats.org/spreadsheetml/2006/main' count='1' uniqueCount='1'><s:si><s:r><s:t xml:space='preserve'> a&amp;b </s:t></s:r></s:si><!--unknown--></s:sst>";let x=Xml::parse(xml).unwrap();assert_eq!(si_text(&x,items(&x).unwrap()[0]).unwrap()," a&b ");assert_eq!(tag(&x.nodes[0],"si"),"s:si");let result=apply(xml,vec![x.attr_patch(0,"count","1","2").unwrap()]).unwrap();assert!(std::str::from_utf8(&result).unwrap().contains("<!--unknown-->"));}
