use super::*;
// All test workbooks are constructed here in memory. Never read the real workbook.
fn fixture()->(Package,Manifest){
    let m=manifest().unwrap();let mut texts=vec!["synthetic".to_string();490];for d in &m.cells{if let Some(i)=d.old_ref{texts[i]=d.old.clone().unwrap();}}texts[36]="shared old index36".into();
    let mut entries=BTreeMap::new();let sst=format!("<?xml version=\"1.0\" encoding=\"UTF-8\"?><sst xmlns=\"{NS}\" xmlns:x=\"urn:unknown\" count=\"1163\" uniqueCount=\"490\">{}<x:extension untouched='yes'/></sst>",texts.iter().enumerate().map(|(i,t)|if i==36{format!("<si><r><rPr><b/></rPr><t xml:space=\"preserve\">{}</t></r></si>",quick_xml::escape::escape(t))}else{format!("<si><t>{}</t></si>",quick_xml::escape::escape(t))}).collect::<String>());entries.insert(PARTS[0].to_string(),sst.into_bytes());
    for sheet in 1..=3{let rows=[0,12,130,110][sheet];let mut xml=format!("<?xml version='1.0'?><worksheet xmlns=\"{NS}\" xmlns:x='urn:unknown'><dimension ref='A1:E{rows}'/><sheetData>");for row in 1..=rows{xml.push_str(&format!("<row r='{row}'>"));for col in b'A'..=b'E'{let c=format!("{}{row}",col as char);let d=m.cells.iter().find(|d|d.sheet==sheet&&d.cell==c);let empty=sheet==3 && ((row==91 && col>=b'C') || (row>=92 && !(row==94 && col==b'C')));if !empty{let reference=d.and_then(|d|d.old_ref).unwrap_or(36);xml.push_str(&format!("<c r='{c}' s='3' t='s'><v>{reference}</v><extLst><x:unknown a='keep'/></extLst></c>"));}else{xml.push_str(&format!("<c r='{c}' s='3'/>"));}}xml.push_str("</row>");}xml.push_str("</sheetData>");if sheet==3{xml.push_str("<conditionalFormatting sqref='A2:E110'>");for i in 0..12{xml.push_str(&format!("<cfRule type='expression' dxfId='{i}' priority='{}'><formula>$B2=\"Intake\"</formula></cfRule>",i+1));}xml.push_str("</conditionalFormatting>");}xml.push_str("<extLst><x:opaque> &amp; unchanged </x:opaque></extLst></worksheet>");entries.insert(PARTS[sheet].into(),xml.into_bytes());}
    entries.insert("xl/styles.xml".into(),format!("<styleSheet xmlns='{NS}'><cellXfs count='4'><xf/><xf/><xf/><xf/></cellXfs></styleSheet>").into_bytes());
    entries.insert("xl/workbook.xml".into(),format!("<workbook xmlns='{NS}' xmlns:r='{REL}'><sheets>{}</sheets></workbook>",m.bindings.iter().enumerate().map(|(i,b)|format!("<sheet name='{}' sheetId='{}' r:id='{}'/>",b[0],i+1,b[1])).collect::<String>()).into_bytes());
    entries.insert("xl/_rels/workbook.xml.rels".into(),format!("<Relationships xmlns='{PKGREL}'>{}</Relationships>",m.bindings.iter().map(|b|format!("<Relationship Id='{}' Type='{REL}/worksheet' Target='{}'/>",b[1],b[2])).collect::<String>()).into_bytes());entries.insert("unknown/protected.bin".into(),vec![0,255,10,1]);for name in ["[Content_Types].xml","_rels/.rels","xl/theme/theme1.xml","docProps/core.xml"]{entries.insert(name.into(),b"<opaque/>".to_vec());}
    let mut writer=ZipWriter::new(Cursor::new(Vec::new()));for(n,b)in entries{writer.start_file(n,SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated)).unwrap();writer.write_all(&b).unwrap();}let bytes=writer.finish().unwrap().into_inner();(package(&bytes).unwrap(),m)
}
// Independently assembled headers, not ZipWriter-normalized metadata.
fn put16(b:&mut [u8],p:usize,v:u16){b[p..p+2].copy_from_slice(&v.to_le_bytes());}
fn put32(b:&mut [u8],p:usize,v:u32){b[p..p+4].copy_from_slice(&v.to_le_bytes());}
fn origin_zip(descriptor:usize)->Vec<u8>{
    let mut compressor=ZipWriter::new(Cursor::new(vec![]));compressor.start_file("protected",SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated)).unwrap();compressor.write_all(b"opaque PK\x03\x04 payload").unwrap();let encoded=compressor.finish().unwrap().into_inner();let p=package(&encoded).unwrap();let e=&p["protected"];let name=b"protected";let mut local=vec![0;30];put32(&mut local,0,0x04034b50);put16(&mut local,4,20);put16(&mut local,6,6|if descriptor>0{8}else{0});put16(&mut local,8,8);put16(&mut local,12,33);if descriptor==0{put32(&mut local,14,e.crc);put32(&mut local,18,e.raw.len() as u32);put32(&mut local,22,e.data.len() as u32);}put16(&mut local,26,name.len() as u16);put16(&mut local,28,520);local.extend_from_slice(name);local.extend_from_slice(&0xa220u16.to_le_bytes());local.extend_from_slice(&516u16.to_le_bytes());local.extend_from_slice(&vec![0xa5;516]);local.extend_from_slice(&e.raw);
    if descriptor>0{if descriptor==16{local.extend_from_slice(&0x08074b50u32.to_le_bytes());}local.extend_from_slice(&e.crc.to_le_bytes());local.extend_from_slice(&(e.raw.len() as u32).to_le_bytes());local.extend_from_slice(&(e.data.len() as u32).to_le_bytes());}
    let cd=local.len();let mut central=vec![0;46];put32(&mut central,0,0x02014b50);put16(&mut central,4,45);put16(&mut central,6,20);put16(&mut central,8,6|if descriptor>0{8}else{0});put16(&mut central,10,8);put16(&mut central,14,33);put32(&mut central,16,e.crc);put32(&mut central,20,e.raw.len() as u32);put32(&mut central,24,e.data.len() as u32);put16(&mut central,28,name.len() as u16);central.extend_from_slice(name);let mut end=vec![0;22];put32(&mut end,0,0x06054b50);put16(&mut end,8,1);put16(&mut end,10,1);put32(&mut end,12,central.len() as u32);put32(&mut end,16,cd as u32);put16(&mut end,20,7);end.extend_from_slice(b"archive");local.extend_from_slice(&central);local.extend_from_slice(&end);local
}
fn originize_all_protected(bytes:&[u8])->Vec<u8>{
    let l=layout(bytes).unwrap();let mut locals=vec![];let mut centrals=vec![];
    for r in &l.records{let offset=locals.len() as u32;let mut local=bytes[r.local.clone()].to_vec();let mut central=bytes[r.central.clone()].to_vec();if !PARTS.contains(&r.name.as_str()){
        let n=u16_at(&local,26).unwrap() as usize;assert_eq!(u16_at(&local,28).unwrap(),0);let mut extra=vec![0xa5;520];put16(&mut extra,0,0xa220);put16(&mut extra,2,516);local.splice(30+n..30+n,extra);put16(&mut local,28,520);put16(&mut local,6,6);put16(&mut central,8,6);put16(&mut central,4,45);put32(&mut central,38,0);
    }put32(&mut central,42,offset);locals.extend_from_slice(&local);centrals.extend_from_slice(&central);}
    let cd=locals.len() as u32;let mut end=bytes[l.eocd..].to_vec();put32(&mut end,12,centrals.len() as u32);put32(&mut end,16,cd);locals.extend_from_slice(&centrals);locals.extend_from_slice(&end);locals
}
#[test]fn origin_bounds_and_metadata_variants(){
    for (host,attrs) in [(45,0),(0x0314,0o100600<<16),(20,1)]{
        let mut bytes=origin_zip(0);let l=layout(&bytes).unwrap();let r=&l.records[0];assert_eq!(r.local.start,0);assert_eq!(r.payload.start,30+9+520);assert_eq!(r.payload.end,r.local.end);assert_eq!(r.central.start,r.local.end);let c=r.central.start;put16(&mut bytes,c+4,host);put32(&mut bytes,c+38,attrs);
        // Asymmetric central extra and nonempty entry comment.
        let l=layout(&bytes).unwrap();let e=l.eocd;let c=l.records[0].central.start;let insert=l.records[0].central.end;bytes.splice(insert..insert,[0x02,0xa2,1,0,7,b'c',b'm',b't']);put16(&mut bytes,c+30,5);put16(&mut bytes,c+32,3);let old=u32_at(&bytes,e+8+12).unwrap();put32(&mut bytes,e+8+12,old+8);
        let p=package(&bytes).unwrap();let mut out=Cursor::new(vec![]);write_zip(&bytes,&BTreeMap::new(),&mut out).unwrap();let q=package(out.get_ref()).unwrap();protected_equal("protected",&p["protected"],&q["protected"]).unwrap();assert_eq!(p["protected"].extra,[0x02,0xa2,1,0,7]);assert_eq!(p["protected"].comment,"cmt");
    }
}
#[test]fn descriptors_and_fail_closed_layouts(){
    for d in [12,16]{let bytes=origin_zip(d);let l=layout(&bytes).unwrap();assert_eq!(l.records[0].local.end-l.records[0].payload.end,d);let mut out=Cursor::new(vec![]);write_zip(&bytes,&BTreeMap::new(),&mut out).unwrap();assert_eq!(bytes,out.into_inner());let mut bad=bytes.clone();bad[l.records[0].payload.end+d-1]^=1;assert!(layout(&bad).is_err());}
    let bytes=origin_zip(0);let l=layout(&bytes).unwrap();let c=l.records[0].central.start;let e=l.eocd;
    for (pos,value) in [(c+20,u32::MAX),(c+24,u32::MAX),(c+42,u32::MAX),(c+42,1),(e+12,u32::MAX),(e+16,u32::MAX),(14,0),(18,0),(22,0),(0,0),(c,0)]{let mut bad=bytes.clone();put32(&mut bad,pos,value);assert!(layout(&bad).is_err(),"{pos}");}
    for (pos,value) in [(e+4,1),(e+6,1),(e+8,u16::MAX),(e+10,u16::MAX),(c+34,1),(c+8,1),(6,1),(8,0),(26,8),(30+9,1),(28,u16::MAX)]{let mut bad=bytes.clone();put16(&mut bad,pos,value);assert!(layout(&bad).is_err(),"{pos}");}
    let mut trailing=bytes.clone();trailing.push(0);assert!(layout(&trailing).is_err());let mut gap=bytes.clone();gap.insert(c,0);put32(&mut gap,e+1+16,(c+1) as u32);assert!(layout(&gap).is_err());
    // Exact documented intervals, parser-only; dummy compressed content is never decoded.
    let mut bounds=origin_zip(0);let old=layout(&bounds).unwrap();let payload=old.records[0].payload.clone();bounds.splice(payload,vec![0;361]);
    bounds.splice(30..39,b"[Content_Types].xml".iter().copied());let central=930;let oldcentral=old.records[0].central.len();bounds.splice(central+46..central+55,b"[Content_Types].xml".iter().copied());let eo=central+oldcentral+10;put16(&mut bounds,26,19);put32(&mut bounds,18,361);put16(&mut bounds,central+28,19);put32(&mut bounds,central+20,361);put32(&mut bounds,eo+12,(oldcentral+10) as u32);put32(&mut bounds,eo+16,central as u32);let r=layout(&bounds).unwrap().records.remove(0);assert_eq!(r.payload,569..930);assert_eq!(r.local,0..930);
    // Two central records sharing one local record, then reverse order / overlap.
    let mut shared=bytes[..e].to_vec();shared.extend_from_slice(&bytes[c..e]);shared.extend_from_slice(&bytes[e..]);let ne=e+(e-c);put16(&mut shared,ne+8,2);put16(&mut shared,ne+10,2);put32(&mut shared,ne+12,((e-c)*2) as u32);assert!(layout(&shared).is_err());
    let mut shared_unique=shared.clone();shared_unique[e+46]=b'X';assert!(layout(&shared_unique).is_err()); // shared offset, distinct names
    let mut reverse=shared_unique.clone();put32(&mut reverse,c+42,1);assert!(layout(&reverse).is_err());
    let mut central_zip64=bytes.clone();central_zip64.splice(e..e,[1,0,0,0]);put16(&mut central_zip64,c+30,4);put32(&mut central_zip64,e+4+12,(e-c+4) as u32);assert!(layout(&central_zip64).is_err());
    for len in [20,24]{let mut bad=origin_zip(16);let l=layout(&bad).unwrap();let c=l.records[0].central.start;let e=l.eocd;bad.splice(c..c,vec![0;len-16]);put32(&mut bad,e+len-16+16,(c+len-16) as u32);assert!(layout(&bad).is_err());}
    for flag in [1,0x40,0x2000]{let mut bad=bytes.clone();put16(&mut bad,6,flag);put16(&mut bad,c+8,flag);assert!(layout(&bad).is_err());}
    assert!(add(usize::MAX,1).is_err());assert!(span(&bytes,usize::MAX,1).is_err());
    for d in [12,16]{let mut bad=origin_zip(d);let l=layout(&bad).unwrap();let c=l.records[0].central.start;let ds=l.records[0].payload.end;put32(&mut bad,c+16,0x08074b50);put32(&mut bad,ds+if d==16{4}else{0},0x08074b50);assert!(layout(&bad).is_err());}
}
#[test]fn every_protected_field_has_named_diagnostic(){let bytes=origin_zip(0);let p=package(&bytes).unwrap();let a=&p["protected"];for field in ["data","raw","method","crc","time","unix","extra","comment","local_record","central_record_except_offset"]{let mut b=a.clone();match field{"data"=>b.data.push(1),"raw"=>b.raw.push(1),"method"=>b.method=zip::CompressionMethod::Stored,"crc"=>b.crc^=1,"time"=>b.time.push('x'),"unix"=>b.unix=Some(0o100644),"extra"=>b.extra.push(1),"comment"=>b.comment.push('x'),"local_record"=>b.local[39]^=1,_=>b.central[4]^=1};assert!(protected_equal("protected",a,&b).unwrap_err().to_string().contains(field));}for pos in [6,39]{let mut b=a.clone();b.local[pos]^=1;assert!(protected_equal("protected",a,&b).is_err());}let mut relocated=a.clone();put32(&mut relocated.central,42,123);protected_equal("protected",a,&relocated).unwrap();}
fn mutated(part:&str,old:&str,new:&str)->(Package,Manifest){let(mut p,m)=fixture();let e=p.get_mut(part).unwrap();let s=String::from_utf8(e.data.clone()).unwrap();assert!(s.contains(old));e.data=s.replacen(old,new,1).into_bytes();(p,m)}
#[test]fn complete_selective_change_preserves_all_original_spans(){let(p,m)=fixture();let changes=transform(&p,&m).unwrap();let mut q=p.clone();for(n,b)in &changes{q.get_mut(n).unwrap().data=b.clone();}verify(&p,&q,&m,&changes).unwrap();assert_eq!(changes.len(),4);}
#[test]fn old36_copy_on_write_target_only(){let bytes=format!("<sst xmlns='{NS}' count='2' uniqueCount='37'>{}<si><r><t xml:space='preserve'> old &amp; text </t></r></si></sst>","<si><t>filler</t></si>".repeat(36));let x=Xml::parse(bytes.as_bytes()).unwrap();let ss=items(&x).unwrap();assert_eq!(si_text(&x,ss[36]).unwrap()," old & text ");let source=format!("<worksheet xmlns='{NS}'><sheetData><row r='1'><c r='A1' t='s'><v>36</v></c><c r='B1' t='s'><v>36</v></c></row></sheetData></worksheet>");let x=Xml::parse(source.as_bytes()).unwrap();let map=cell_map(&x).unwrap();let v=x.children(map["A1"],"v")[0];let n=&x.nodes[v];let changed=apply(x.bytes,vec![Patch{start:n.open_end,end:n.close_start,text:b"37".to_vec()}]).unwrap();let y=Xml::parse(&changed).unwrap();let ym=cell_map(&y).unwrap();assert_eq!(x.raw(map["B1"]),y.raw(ym["B1"]));assert_eq!(y.content(y.children(ym["A1"],"v")[0]).unwrap(),"37");}
#[test]fn wrong_old_ref_blocked(){let(p,m)=mutated(PARTS[1],"<v>12</v>","<v>36</v>");assert!(transform(&p,&m).is_err());}
#[test]fn wrong_old_text_blocked(){let(p,m)=mutated(PARTS[0],"<t>Analyse</t>","<t>WRONG</t>");assert!(transform(&p,&m).is_err());}
#[test]fn formula_blocked(){let(p,m)=mutated(PARTS[1],"<v>12</v>","<f>1+1</f><v>12</v>");assert!(transform(&p,&m).is_err());}
#[test]fn new_cell_conflict_blocked(){let(p,m)=mutated(PARTS[3],"</row>","<c r='F1' t='s'><v>36</v></c></row>");assert!(transform(&p,&m).is_err());}
#[test]fn malformed_ref_blocked(){for c in ["A0","A01","a1","A-1","1","A1:B1","XFE1","A1048577","AAA"]{assert!(coord(c).is_err(),"{c}");}let(p,m)=mutated(PARTS[1],"r='A1'","r='A01'");assert!(transform(&p,&m).is_err());}
#[test]fn duplicate_and_excluded_targets_blocked(){let(_,mut m)=fixture();m.cells[1]=m.cells[0].clone();assert!(validate_deltas(&m).is_err());let mut m=manifest().unwrap();m.cells[0].cell="E3".into();assert!(validate_deltas(&m).is_err());}
#[test]fn unknown_target_and_allowlist_mutation_blocked(){let mut m=manifest().unwrap();m.cells[0].sheet=4;assert!(validate_deltas(&m).is_err());let mut m=manifest().unwrap();m.allowed_parts.push("xl/styles.xml".into());assert!(validate_deltas(&m).is_err());let json=APPROVED.replace("Analysing","Fake");assert!(check_manifest(&json).is_err());}
#[test]fn relation_binding_blocked(){let(p,m)=mutated("xl/_rels/workbook.xml.rels","worksheets/sheet1.xml","worksheets/evil.xml");assert!(transform(&p,&m).is_err());}
#[test]fn namespace_and_malformed_xml_blocked(){assert!(Xml::parse(b"<x><y></x>").is_err());let(p,m)=mutated(PARTS[3],NS,"urn:wrong");assert!(transform(&p,&m).is_err());assert!(Xml::parse(b"<!DOCTYPE x><x/>").is_err());}
#[test]fn independent_preservation_tamper_detected(){let(p,m)=fixture();let changes=transform(&p,&m).unwrap();let mut q=p.clone();for(n,b)in &changes{q.get_mut(n).unwrap().data=b.clone();}q.get_mut("unknown/protected.bin").unwrap().raw.push(1);assert!(verify(&p,&q,&m,&changes).is_err());}
#[test]fn source_hash_and_no_writes_on_failure(){let source=b"wrong hash";assert_ne!(hash(source),manifest().unwrap().sources[0][1]);assert!(no_clobber_decision(true,true,true).is_err());assert!(no_clobber_decision(false,false,true).is_err());assert!(no_clobber_decision(false,true,false).is_err());assert!(no_clobber_decision(false,true,true).is_ok());assert_eq!(source,b"wrong hash");}
#[test]fn independent_dos_origin_passthrough_all_eight_fields(){let bytes=origin_zip(0);let original=package(&bytes).unwrap();assert_eq!(original["protected"].unix,None);let mut out=Cursor::new(vec![]);write_zip(&bytes,&BTreeMap::new(),&mut out).unwrap();let copied=package(out.get_ref()).unwrap();protected_equal("protected",&original["protected"],&copied["protected"]).unwrap();assert_eq!(bytes,out.into_inner());}
#[test]fn synthetic_candidate_actual_zip_reopen_and_no_clobber(){
    let(p,m)=fixture();let changes=transform(&p,&m).unwrap();let mut source=ZipWriter::new(Cursor::new(vec![]));
    for(n,e)in &p{source.start_file(n,SimpleFileOptions::default().compression_method(e.method)).unwrap();source.write_all(&e.data).unwrap();}
    let bytes=originize_all_protected(&source.finish().unwrap().into_inner());let original=package(&bytes).unwrap();assert_eq!(original.values().filter(|e|e.unix.is_none()).count(),8);let before=hash(&bytes);let mut out=Cursor::new(vec![]);write_zip(&bytes,&changes,&mut out).unwrap();let candidate=package(out.get_ref()).unwrap();let(preserved,_)=verify(&original,&candidate,&m,&changes).unwrap();assert_eq!(preserved.len(),8);assert!(original.iter().any(|(n,e)|!changes.contains_key(n)&&e.central[42..46]!=candidate[n].central[42..46]),"protected offsets actually relocated");assert_eq!(candidate.values().filter(|e|e.unix.is_none()).count(),8);assert_eq!(before,hash(&bytes));assert!(no_clobber_decision(false,true,true).is_ok());assert!(no_clobber_decision(true,true,true).is_err()); // pure pre-existing/race-created decision; persist_noclobber remains unchanged
}
#[test]fn metadata_and_unknown_spans_tamper_blocked(){let(p,m)=fixture();let changes=transform(&p,&m).unwrap();let mut q=p.clone();for(n,b)in &changes{q.get_mut(n).unwrap().data=b.clone();}let e=q.get_mut(PARTS[3]).unwrap();e.data=String::from_utf8(e.data.clone()).unwrap().replace("A2:G110","A2:H110").into_bytes();assert!(verify(&p,&q,&m,&changes).is_err());}
#[test]fn escape_space_and_prefix_preserved(){let xml=b"<?xml version='1.0'?><s:sst xmlns:s='http://schemas.openxmlformats.org/spreadsheetml/2006/main' count='1' uniqueCount='1'><s:si><s:r><s:t xml:space='preserve'> a&amp;b </s:t></s:r></s:si><!--unknown--></s:sst>";let x=Xml::parse(xml).unwrap();assert_eq!(si_text(&x,items(&x).unwrap()[0]).unwrap()," a&b ");assert_eq!(tag(&x.nodes[0],"si"),"s:si");let result=apply(xml,vec![x.attr_patch(0,"count","1","2").unwrap()]).unwrap();assert!(std::str::from_utf8(&result).unwrap().contains("<!--unknown-->"));}
